In [18]:
import sklearn
from sklearn.model_selection import train_test_split
import numpy as np

## Numpy tutorial to follow

https://cs231n.github.io/python-numpy-tutorial/

In [47]:
X = np.random.rand(1,50)

In [48]:
X.shape

(1L, 50L)

In [49]:
f12 = lambda x: (1+x)/(0.7*np.sin(x))

In [50]:
y=f12(X)

In [53]:
y.shape

(1L, 50L)

In [108]:
X, y = np.random.rand(25),np.random.rand(25)

In [109]:
X.shape

(25L,)

In [110]:
X

array([ 0.24443966,  0.55479997,  0.93416261,  0.6591466 ,  0.62833965,
        0.02044665,  0.50262629,  0.27410194,  0.68259631,  0.93088895,
        0.69620322,  0.38491806,  0.29699359,  0.82213479,  0.75622945,
        0.36968441,  0.77204783,  0.51756553,  0.5086602 ,  0.40257403,
        0.58689154,  0.24840984,  0.11680242,  0.08762855,  0.83404396])

In [111]:
y.shape

(25L,)

In [112]:
y

array([ 0.49119707,  0.84192313,  0.82439317,  0.80221224,  0.52302889,
        0.09120661,  0.4971581 ,  0.90391319,  0.45162699,  0.91390957,
        0.28496535,  0.94010166,  0.67860535,  0.79403834,  0.5437419 ,
        0.71903009,  0.36155257,  0.773329  ,  0.14177005,  0.28343708,
        0.43550224,  0.54806447,  0.09912257,  0.83446397,  0.53016249])

In [113]:
X_train,y_train,x_test,y_test=train_test_split(X,y,test_size=0.5)

In [114]:
X_train.shape

(12L,)

In [115]:
y_train.shape

(13L,)

In [116]:
x_test

array([ 0.09120661,  0.49119707,  0.14177005,  0.79403834,  0.28496535,
        0.84192313,  0.80221224,  0.90391319,  0.43550224,  0.5437419 ,
        0.82439317,  0.09912257])

In [117]:
y_test

array([ 0.91390957,  0.36155257,  0.67860535,  0.28343708,  0.52302889,
        0.54806447,  0.71903009,  0.94010166,  0.773329  ,  0.4971581 ,
        0.53016249,  0.83446397,  0.45162699])